# Generated by Django 4.2.22 on 2025-06-05 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("advisor_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="id",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="google_credentials_json",
            field=models.TextField(
                blank=True,
                help_text="Stores Google OAuth credentials as JSON. Handle with care.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="e.g., London,UK or 75001,US or City Name",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="profile",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
